import datetime

def generate_institutional_report(portfolio, backtest_results, regime):
    """
    Phase 40: Final Institutional Report Generator.
    Compiles all data into a professional Grade-A research document.
    """
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    filename = f"Institutional_Research_Report_{date_str}.md"
    
    with open(filename, "w", encoding="utf-8") as f:
        # 1. Header
        f.write(f"# 🏛️ INSTITUTIONAL RESEARCH REPORT\n")
        f.write(f"**Date**: {date_str}\n")
        f.write(f"**Market Regime**: {regime}\n")
        f.write(f"**Strategy Mode**: Adaptive Multi-Factor\n")
        f.write("---\n\n")
        
        # 2. Executive Summary
        cagr = backtest_results.get("CAGR", 0)
        net_cagr = backtest_results.get("NetCAGR", 0)
        alpha = backtest_results.get("NetAlpha", 0)
        
        f.write("## 1. EXECUTIVE SUMMARY\n")
        f.write(f"- **projected CAGR (Gross)**: {cagr:.1f}%\n")
        f.write(f"- **Real CAGR (Net of Slippage)**: {net_cagr:.1f}%\n")
        f.write(f"- **Net Alpha vs Nifty**: {alpha:+.1f}%\n")
        
        if alpha > 0:
            f.write("- **Verdict**: **OVERWEIGHT** (System Detects Alpha)\n")
        else:
            f.write("- **Verdict**: **NEUTRAL/UNDERWEIGHT** (No Edge Detected)\n")
        f.write("\n")
        
        # 3. Portfolio Allocation
        f.write("## 2. MODEL PORTFOLIO ALLOCATION\n")
        f.write(f"| Ticker | Sector | Weight | Score | Status |\n")
        f.write(f"|---|---|---|---|---|\n")
        
        for s in portfolio:
            sym = s.get("Symbol", "")
            sec = s.get("Sector", "")
            w = s.get("Target_Weight%", 0)
            score = s.get("Score", 0)
            stat = s.get("Compounder_Status", "")
            f.write(f"| {sym} | {sec} | {w}% | {score} | {stat} |\n")
            
        f.write("\n")
        
        # 4. Risk Profile
        f.write("## 3. RISK & LIQUIDITY PROFILE\n")
        max_dd = backtest_results.get("MaxDD", 0)
        sharpe = backtest_results.get("Sharpe", 0)
        
        f.write(f"- **Max History Drawdown**: {max_dd:.1f}%\n")
        f.write(f"- **Sharpe Ratio**: {sharpe:.2f}\n")
        
        f.write("\n")
        f.write("> *Generated by Sovereign Quantitative Engine (Phase 40)*\n")
        
    print(f"\n📄 REPORT GENERATED: {filename}")
    return filename
