"""
Sovereign Terminal — Field Mapping Source of Truth
Bidirectional field mappings between Python/Scoring/Screener keys (capitalized/camelCase/with symbols)
and database column names (snake_case).
"""

FIELD_MAPPING = {
    "Symbol": "symbol",
    "Price": "price",
    "Sector": "sector",
    "Score": "score",
    "F_Score": "f_score",
    "Rating": "rating",
    "Buy_Below": "buy_below",
    "Stop_Loss": "stop_loss",
    "Target_1": "target_1",
    "Target_2": "target_2",
    "Sales_Growth_TTM%": "sales_growth",
    "ROE%": "roe",
    "PEG_Ratio": "peg_ratio",
    "Debt_Equity": "debt_equity",
    "RSI": "rsi",
    "Smart_Money%": "smart_money",
    "Market_Cap_Cr": "market_cap_cr",
    "CFO_PAT_Ratio": "cfo_pat_ratio",
    "Sales_Growth_5Y%": "sales_cagr_5y",
    "Avg_ROE_5Y%": "avg_roe_5y",
    "PE_Ratio": "pe_ratio",
    "Down_From_52W_High%": "down_from_52w",
    "RS_Rating": "rs_rating",
    "Earnings_Accel": "earnings_accel",
    "Sector_Leader": "sector_leader",
    "Graham_Number": "graham_number",
    "Value_Gap%": "value_gap",
    "Technical_Signal": "technical_signal",
    "Analyst_Rating": "analyst_rating",
    "Analyst_Upside%": "analyst_upside",
    "Promoter_Holding%": "promoter_holding",
    "Inst_Holding%": "inst_holding",
    "ATR": "atr",
    "Stop_Loss_ATR": "stop_loss_atr",
    "Max_Qty_1L": "max_qty_1l",
    "As_Of_Date": "as_of_date",
    "updated_at": "updated_at",
    "Conviction_Score": "conviction_score",
    "Conviction_Boost": "conviction_boost",
    "Institutional_Interest": "institutional_interest",
    "Super_Investors": "super_investors",
    "Data_Quality": "data_quality",
    "Data_Confidence": "data_confidence",
    "F_Score_Method": "f_score_method",
    "Backtest_CAGR": "backtest_cagr",
    "Backtest_Win_Rate": "backtest_win_rate",
    "Backtest_Max_DD": "backtest_max_dd",
    "Backtest_Sharpe": "backtest_sharpe",
    "ML_Predicted_Return": "ml_predicted_return",
    "SHAP_Breakdown": "shap_breakdown",
    "High_52W": "high_52w",
    "Low_52W": "low_52w",
    "Pledge_Pct": "pledge_pct",
    "Piotroski_Score": "piotroski_score",
    "ROCE_pct": "roce",
    "Median_PAT_Growth_5Y_pct": "median_pat_growth",
    "ml_rank_score": "ml_rank_score",
    "Ret_1M": "ret_1m",
    "Ret_3M": "ret_3m",
    "Ret_6M": "ret_6m",
    "Vol_Breakout": "vol_breakout",
    "Dist_From_52W_High": "dist_from_52w_high",
    "Revenue_CAGR_3Y": "revenue_cagr_3y",
    "Revenue_CAGR_5Y": "revenue_cagr_5y",
    "PAT_CAGR_3Y": "pat_cagr_3y",
    "PAT_CAGR_5Y": "pat_cagr_5y",
    "EPS_CAGR_3Y": "eps_cagr_3y",
    "EPS_CAGR_5Y": "eps_cagr_5y",
    "CAGR_Consistency": "cagr_consistency",
    "Dividend_Yield": "dividend_yield",
    "Dividend_Payout": "dividend_payout",
    "Cap_Category": "cap_category",
    "Data_Quality_Flags": "data_quality_flags",
}

# Reverse mapping for converting database snake_case back to display/python fields
REVERSE_FIELD_MAPPING = {v: k for k, v in FIELD_MAPPING.items()}
