from fastapi import APIRouter, Depends
import subprocess
import json
import os
from modules.dependencies import get_api_key

router = APIRouter(prefix="/swarm", tags=["swarm"])

RUFLO_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../services/ruflo-orchestrator"))

@router.get("/status")
async def get_swarm_status():
    """Proxy swarm status from Ruflo microservice."""
    try:
        # Run ruflo status command
        result = subprocess.run(
            ["npx.cmd", "ruflo", "swarm", "status", "--format", "json"],
            cwd=RUFLO_DIR,
            capture_output=True,
            text=True,
            shell=True
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
        else:
            return {"status": "offline", "error": result.stderr}
    except Exception as e:
        return {"status": "error", "message": str(e)}

@router.get("/alerts")
async def get_swarm_alerts():
    """Fetch recent alerts generated by the Regime-Monitor swarm."""
    # For now, mock alerts until the reporter agent is fully wired to a DB or webhook
    return [
        {
            "id": "alert_001",
            "type": "REGIME_SHIFT",
            "sector": "Energy",
            "label": "G",
            "confidence": 0.92,
            "message": "Strong volume breakout in Energy sector. B/G logic confirmed via Sona Memory."
        }
    ]
