"""
llm_validator.py

Validates stock investment theses generated by Large Language Models against
the raw mathematical data vectors used in the generation prompt.

Prevents AI hallucination of metrics (ratios, percentages, multiples) before
rendering on the Institutional Terminal.
"""

import difflib
import math
import re
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ValidationReport:
    """Dataclass capturing the full safety envelope of an LLM generation."""

    is_valid: bool
    confidence_score: float
    flagged_claims: list[dict[str, Any]] = field(default_factory=list)
    sanitized_thesis: str = ""
    audit_trail: list[str] = field(default_factory=list)


class FactValidator:
    """
    Scans LLM-generated narrative against hard quantitative bounds, automatically
    repairing hallucinations or rejecting statistically invalid generations.
    """

    def __init__(self, tolerance_pct: float = 15.0):
        self.tolerance_pct = tolerance_pct
        # Regex to catch:
        # - percentages: 45.3% or 45%
        # - multiples: 2.3x or 15x
        # - raw decimals: 4.56
        # - integers: 400
        # Ignore years (like 2026, 2025)
        self.number_pattern = re.compile(
            r"\b(?!(?:19|20)\d{2}\b)(\d+(?:\.\d+)?)(%|x)?\b", re.IGNORECASE
        )

    def _fuzzy_match_key(self, context_words: list[str], data_keys: list[str]) -> str | None:
        """Finds the most likely data vector key for a given numeric claim."""
        best_match = None
        highest_ratio = 0.0

        # Build sentences around the number to guess the context
        context_str = " ".join(context_words).lower()

        for key in data_keys:
            # Clean up the key for comparison (e.g., 'sales_cagr_5y' -> 'sales cagr 5y')
            clean_key = key.lower().replace("_", " ")

            # Simple gestalt pattern matching
            ratio = difflib.SequenceMatcher(None, context_str, clean_key).ratio()

            # Boost ratio if exact substring matches
            if clean_key in context_str or any(word in context_str for word in clean_key.split()):
                ratio += 0.3

            if ratio > highest_ratio:
                highest_ratio = ratio
                best_match = key

        return best_match if highest_ratio > 0.4 else None

    def _get_context_window(self, text: str, match_obj, window_size: int = 40) -> list[str]:
        """Extracts words surrounding a match to feed the fuzzy matcher."""
        start_idx = max(0, match_obj.start() - window_size)
        end_idx = min(len(text), match_obj.end() + window_size)
        window = text[start_idx:end_idx]
        return re.findall(r"\b[a-zA-Z]+\b", window)

    def validate(self, thesis: str, data_vector: dict) -> ValidationReport:
        """
        Cross-references every number in the LLM thesis against the closest conceptual
        metric in the source data_vector.
        """
        audit_trail = []
        flagged_claims = []

        sanitized_thesis = thesis
        audit_trail.append("Initialized FactValidator.")

        # Flatten dictionary keys for matching (assuming simple depth 1 or 2 dictionary)
        flat_data = {}
        for k, v in data_vector.items():
            if isinstance(v, (int, float)):
                if not math.isnan(v) and not math.isinf(v):
                    flat_data[k] = float(v)
            elif isinstance(v, str):
                try:  # try cast to number if it's a string representation of a number
                    val = float(v.replace(",", "").replace("%", ""))
                    flat_data[k] = val
                except ValueError:
                    pass
            elif isinstance(v, dict):  # simple flattening of 1 level nested dicts
                for nk, nv in v.items():
                    if isinstance(nv, (int, float)) and not math.isnan(nv) and not math.isinf(nv):
                        flat_data[f"{k}_{nk}"] = float(nv)

        if not flat_data:
            audit_trail.append("Warning: No numerical data found in data_vector. Cannot validate.")
            return ValidationReport(True, 1.0, [], thesis, audit_trail)

        data_keys = list(flat_data.keys())
        audit_trail.append(
            f"Ready to cross-reference against {len(data_keys)} numerical data points."
        )

        # Find all numbers in the thesis
        matches = list(self.number_pattern.finditer(thesis))

        if not matches:
            audit_trail.append("No numerical claims detected in thesis.")
            return ValidationReport(True, 1.0, [], thesis, audit_trail)

        # Process matches in reverse order so string replacements don't break offsets
        for match in reversed(matches):
            raw_str = match.group(0)
            num_val = float(match.group(1))
            suffix = match.group(2) or ""

            # Skip very small integers that are likely conversational (e.g., "The 3 main factors...")
            if num_val < 10 and num_val.is_integer() and not suffix:
                audit_trail.append(f"Skipping generic small integer '{raw_str}'")
                continue

            context = self._get_context_window(thesis, match)
            best_key = self._fuzzy_match_key(context, data_keys)

            if not best_key:
                audit_trail.append(f"Claim [{raw_str}] -> No matching data context found. Passing.")
                continue

            expected_val = flat_data[best_key]

            # Handle zero comparison safely
            if expected_val == 0:
                deviation_pct = 100.0 if num_val != 0 else 0.0
            else:
                deviation_pct = abs((num_val - expected_val) / expected_val) * 100.0

            audit_trail.append(
                f"Claim [{raw_str}] -> Matched to '{best_key}' ({expected_val:.2f}). Deviation: {deviation_pct:.1f}%"
            )

            if deviation_pct > self.tolerance_pct:
                severity = "HIGH" if deviation_pct > 50 else "MEDIUM"

                # Record the semantic violation
                flagged_claims.append(
                    {
                        "claim": raw_str,
                        "expected": expected_val,
                        "matched_key": best_key,
                        "deviation_pct": deviation_pct,
                        "severity": severity,
                    }
                )

                # Sanitize the thesis string
                # Format the expected value nicely based on the original hallucination
                if suffix == "%":
                    correction = f"{expected_val:.1f}%"
                elif suffix == "x" or suffix == "X":
                    correction = f"{expected_val:.1f}x"
                elif num_val.is_integer():
                    correction = f"{int(round(expected_val))}"
                else:
                    correction = f"{expected_val:.2f}"

                audit_trail.append(
                    f"  -> HALLUCINATION CAUGHT: Rewriting {raw_str} to {correction}"
                )

                start, end = match.span()
                sanitized_thesis = sanitized_thesis[:start] + correction + sanitized_thesis[end:]

        # Calculate final confidence
        total_claims = len(matches)
        violations = len(flagged_claims)
        confidence = max(0.0, 1.0 - (violations / total_claims)) if total_claims > 0 else 1.0

        is_valid = confidence > 0.5  # Fail entirely if more than half the numbers are hallucinated

        if violations > 0:
            audit_trail.append(
                f"Validation complete. Caught {violations} hallucinations. Confidence degraded to {confidence:.2f}"
            )
        else:
            audit_trail.append(
                "Validation complete. Thesis passed all quantitative integrity checks."
            )

        return ValidationReport(
            is_valid=is_valid,
            confidence_score=confidence,
            flagged_claims=flagged_claims,
            sanitized_thesis=sanitized_thesis,
            audit_trail=audit_trail,
        )


def patch_thesis(thesis: str, report: ValidationReport) -> str:
    """
    Applies the validation report to visually flag the thesis based on its structural integrity.
    """
    if not report.is_valid:
        return "[AI-Rejected] The generated thesis contained severe quantitative hallucinations and failed structural audit."

    if report.flagged_claims:
        return f"{report.sanitized_thesis.strip()}\n\n[AI-Flagged: Auto-corrected {len(report.flagged_claims)} numerical deviations from source data]"

    return f"{thesis.strip()}\n\n[AI-Verified]"


# --- Demonstration block ---
if __name__ == "__main__":
    # Test vector simulating a database row
    test_vector = {
        "score": 85.0,
        "sales_growth": 25.4,
        "roe": 18.2,
        "pe_ratio": 30.5,
        "value_gap": -5.1,
    }

    # Simulating LLM hallucination (Invented 35.4% sales growth & 120 ROE)
    hallucinated_thesis = (
        "This company shows tremendous fundamental strength with an impressive 35.4% "
        "sales growth trajectory over the past year. Furthermore, it generates massive "
        "shareholder value operating at a 120% ROE. Finally, trading at just 30.2x earnings, "
        "it possesses an elite Sovereign score of 85."
    )

    validator = FactValidator(tolerance_pct=15.0)
    report = validator.validate(hallucinated_thesis, test_vector)

    print("--- Original LLM Output ---")
    print(hallucinated_thesis)

    print("\n--- Validation Audit Trail ---")
    for log in report.audit_trail:
        print(f">> {log}")

    print("\n--- Sanitized Output ---")
    patched = patch_thesis(hallucinated_thesis, report)
    print(patched)
