import os

from pathlib import Path



# List of NSE stocks to screen

# Expanded to include specific sectors: Renewables, Defense, EMS, Tech

# CORRECTIONS APPLIED: Fixed outdated/incorrect symbols

PROJECT_ROOT = Path(__file__).resolve().parent

TICKER_LIST_PATH = Path(os.getenv("TICKER_LIST_PATH", str(PROJECT_ROOT / "ticker_list.py")))

NIFTY_500_CSV_PATH = Path(

    os.getenv("NIFTY_500_CSV_PATH", str(PROJECT_ROOT / "MW-NIFTY-500-12-Feb-2026.csv"))

)

NIFTY_MICROCAP_CSV_PATH = Path(

    os.getenv(

        "NIFTY_MICROCAP_CSV_PATH",

        str(PROJECT_ROOT / "MW-NIFTY-MICROCAP-250-12-Feb-2026.csv"),

    )

)

NIFTY_MQ50_CSV_PATH = Path(

    os.getenv(

        "NIFTY_MQ50_CSV_PATH",

        str(PROJECT_ROOT / "MW-NIFTY500-MULTICAP-MOMENTUM-QUALITY-50-12-Feb-2026.csv"),

    )

)



TICKERS = [
    "RELIANCE.NS",
    "BHARTIARTL.NS",
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "SBIN.NS",
    "TCS.NS",
    "BAJFINANCE.NS",
    "LT.NS",
    "LICI.NS",
    "HINDUNILVR.NS",
    "SUNPHARMA.NS",
    "TITAN.NS",
    "INFY.NS",
    "KOTAKBANK.NS",
    "ADANIENT.NS",
    "MARUTI.NS",
    "ADANIPOWER.NS",
    "AXISBANK.NS",
    "ADANIPORTS.NS",
    "M&M.NS",
    "HCLTECH.NS",
    "ITC.NS",
    "ULTRACEMCO.NS",
    "HAL.NS",
    "BAJAJ-AUTO.NS",
    "NTPC.NS",
    "JSWSTEEL.NS",
    "BAJAJFINSV.NS",
    "ETERNAL.NS",
    "ONGC.NS",
    "NESTLEIND.NS",
    "COALINDIA.NS",
    "HINDZINC.NS",
    "POWERGRID.NS",
    "DIVISLAB.NS",
    "SHRIRAMFIN.NS",
    "DMART.NS",
    "ASIANPAINT.NS",
    "TATASTEEL.NS",
    "GRASIM.NS",
    "HINDALCO.NS",
    "ADANIGREEN.NS",
    "EICHERMOT.NS",
    "SOLARINDS.NS",
    "TVSMOTOR.NS",
    "INDIGO.NS",
    "IOC.NS",
    "TORNTPHARM.NS",
    "HYUNDAI.NS",
    "SBILIFE.NS",
    "WIPRO.NS",
    "MOTHERSON.NS",
    "ADANIENSOL.NS",
    "IDEA.NS",
    "DLF.NS",
    "PIDILITIND.NS",
    "CHOLAFIN.NS",
    "ABB.NS",
    "TATACAP.NS",
    "JIOFIN.NS",
    "TRENT.NS",
    "ICICIAMC.NS",
    "BHEL.NS",
    "UNIONBANK.NS",
    "BOSCHLTD.NS",
    "POWERINDIA.NS",
    "CGPOWER.NS",
    "SIEMENS.NS",
    "CUMMINSIND.NS",
    "TECHM.NS",
    "VBL.NS",
    "BPCL.NS",
    "PNB.NS",
    "APOLLOHOSP.NS",
    "BANKBARODA.NS",
    "BAJAJHLDNG.NS",
    "BRITANNIA.NS",
    "GROWW.NS",
    "LODHA.NS",
    "LENSKART.NS",
    "INDIANB.NS",
    "TATAPOWER.NS",
    "JINDALSTEL.NS",
    "PFC.NS",
    "HDFCLIFE.NS",
    "GAIL.NS",
    "MUTHOOTFIN.NS",
    "ZYDUSLIFE.NS",
    "TMPV.NS",
    "CIPLA.NS",
    "CANBK.NS",
    "LGEINDIA.NS",
    "GVT&D.NS",
    "ENRIN.NS",
    "ABCAPITAL.NS",
    "IRFC.NS",
    "PAYTM.NS",
    "HEROMOTOCO.NS",
    "VEDL.NS",
    "MARICO.NS",
    "HDFCAMC.NS",
    "INDHOTEL.NS",
    "OFSS.NS",
    "INDIAMART.NS",
    "UNITDSPR.NS",
    "LLOYDSME.NS",
    "LAURUSLABS.NS",
    "GMRAIRPORT.NS",
    "TATACONSUM.NS",
    "ASHOKLEY.NS",
    "INDUSTOWER.NS",
    "AMBUJACEM.NS",
    "MAZDOCK.NS",
    "IDBI.NS",
    "MEESHO.NS",
    "JSWENERGY.NS",
    "MAXHEALTH.NS",
    "LUPIN.NS",
    "MANKIND.NS",
    "AUROPHARMA.NS",
    "NYKAA.NS",
    "DRREDDY.NS",
    "BHARATFORG.NS",
    "GODREJCP.NS",
    "PERSISTENT.NS",
    "COFORGE.NS",
    "MCX.NS",
    "FEDERALBNK.NS",
    "NAUKRI.NS",
    "SHREECEM.NS",
    "RECLTD.NS",
    "POLICYBZR.NS",
    "OIL.NS",
    "AUBANK.NS",
    "LTF.NS",
    "INDUSINDBK.NS",
    "SAIL.NS",
    "JSWINFRA.NS",
    "NAM-INDIA.NS",
    "BHARTIHEXA.NS",
    "NHPC.NS",
    "HINDPETRO.NS",
    "SRF.NS",
    "ICICIGI.NS",
    "WAAREEENER.NS",
    "IDFCFIRSTB.NS",
    "NTPCGREEN.NS",
    "APARINDS.NS",
    "NMDC.NS",
    "SWIGGY.NS",
    "HAVELLS.NS",
    "UNOMINDA.NS",
    "YESBANK.NS",
    "BAJAJHFL.NS",
    "ASTERDM.NS",
    "GLENMARK.NS",
    "FORTIS.NS",
    "WELCORP.NS",
    "ICICIPRULI.NS",
    "PHOENIXLTD.NS",
    "NATIONALUM.NS",
    "OBEROIRLTY.NS",
    "PRESTIGE.NS",
    "DABUR.NS",
    "ATGL.NS",
    "MAHABANK.NS",
    "BANKINDIA.NS",
    "RBLBANK.NS",
    "TORNTPOWER.NS",
    "SBICARD.NS",
    "IOB.NS",
    "BIOCON.NS",
    "MOTILALOFS.NS",
    "ATHERENERG.NS",
    "ALKEM.NS",
    "SUZLON.NS",
    "SCHAEFFLER.NS",
    "APLAPOLLO.NS",
    "GICRE.NS",
    "KALYANKJIL.NS",
    "JSL.NS",
    "COROMANDEL.NS",
    "GODREJPROP.NS",
    "HDBFS.NS",
    "BERGEPAINT.NS",
    "ABBOTINDIA.NS",
    "MRF.NS",
    "LINDEINDIA.NS",
    "PIRAMALFIN.NS",
    "ANTHEM.NS",
    "MFSL.NS",
    "TIINDIA.NS",
    "SUNDARMFIN.NS",
    "M&MFIN.NS",
    "FACT.NS",
    "GLAXO.NS",
    "FLUOROCHEM.NS",
    "IPCALAB.NS",
    "TATACOMM.NS",
    "COLPAL.NS",
    "HINDCOPPER.NS",
    "SONACOMS.NS",
    "GLAND.NS",
    "VMM.NS",
    "UPL.NS",
    "360ONE.NS",
    "BDL.NS",
    "MPHASIS.NS",
    "KEI.NS",
    "PREMIERENE.NS",
    "CPPLUS.NS",
    "BALKRISIND.NS",
    "AEGISLOG.NS",
    "AJANTPHARM.NS",
    "RVNL.NS",
    "AIIL.NS",
    "PETRONET.NS",
    "THERMAX.NS",
    "STLTECH.NS",
    "POONAWALLA.NS",
    "PAGEIND.NS",
    "COCHINSHIP.NS",
    "KPRMILL.NS",
    "GODREJIND.NS",
    "JKCEMENT.NS",
    "ENDURANCE.NS",
    "JBCHEPHARM.NS",
    "VOLTAS.NS",
    "CONCOR.NS",
    "MEDANTA.NS",
    "NIACL.NS",
    "IRCTC.NS",
    "CUPID.NS",
    "PWL.NS",
    "NLCINDIA.NS",
    "HFCL.NS",
    "PATANJALI.NS",
    "3MINDIA.NS",
    "ANANDRATHI.NS",
    "EMCURE.NS",
    "LTTS.NS",
    "EXIDEIND.NS",
    "HUDCO.NS",
    "WOCKPHARMA.NS",
    "PTCIL.NS",
    "CRISIL.NS",
    "UBL.NS",
    "DELHIVERY.NS",
    "HSCL.NS",
    "NUVAMA.NS",
    "SAILIFE.NS",
    "STARHEALTH.NS",
    "KARURVYSYA.NS",
    "ITCHOTELS.NS",
    "ESCORTS.NS",
    "DALBHARAT.NS",
    "HEXT.NS",
    "TATATECH.NS",
    "TATAINVEST.NS",
    "LALPATHLAB.NS",
    "IREDA.NS",
    "GODFRYPHLP.NS",
    "KIRLOSENG.NS",
    "AEGISVOPAK.NS",
    "HONAUT.NS",
    "JUBLFOOD.NS",
    "PNBHOUSING.NS",
    "BLUESTARCO.NS",
    "NETWEB.NS",
    "UCOBANK.NS",
    "MANAPPURAM.NS",
    "LICHSGFIN.NS",
    "MRPL.NS",
    "ABSLAMC.NS",
    "SHYAMMETL.NS",
    "IKS.NS",
    "REDINGTON.NS",
    "CRAFTSMAN.NS",
    "NEULANDLAB.NS",
    "ACMESOLAR.NS",
    "PPLPHARMA.NS",
    "RUBICON.NS",
    "GRSE.NS",
    "CHOLAHLDNG.NS",
    "SCHNEIDER.NS",
    "ZFCVINDIA.NS",
    "CENTRALBK.NS",
    "IIFL.NS",
    "TVSHLTD.NS",
    "ANGELONE.NS",
    "IFCI.NS",
    "RRKABEL.NS",
    "APOLLOTYRE.NS",
    "BANDHANBNK.NS",
    "CGCL.NS",
    "ITI.NS",
    "ACUTAAS.NS",
    "URBANCO.NS",
    "SJVN.NS",
    "METROBRAND.NS",
    "HATSUN.NS",
    "SUNDRMFAST.NS",
    "PGHH.NS",
    "MSUMI.NS",
    "ASAHIINDIA.NS",
    "KPIL.NS",
    "AWL.NS",
    "SANSERA.NS",
    "PFOCUS.NS",
    "GABRIEL.NS",
    "GILLETTE.NS",
    "ACC.NS",
    "GODIGIT.NS",
    "CUB.NS",
    "FORCEMOT.NS",
    "TIMKEN.NS",
    "IRB.NS",
    "NBCC.NS",
    "JYOTICNC.NS",
    "MTARTECH.NS",
    "ANANTRAJ.NS",
    "TDPOWERSYS.NS",
    "CREDITACC.NS",
    "AFFLE.NS",
    "CEMPRO.NS",
    "EMMVEE.NS",
    "BELRISE.NS",
    "BRIGADE.NS",
    "TATAELXSI.NS",
    "IGL.NS",
    "SAGILITY.NS",
    "GRANULES.NS",
    "CAPLIPOINT.NS",
    "CHENNPETRO.NS",
    "PFIZER.NS",
    "AADHARHFC.NS",
    "SHRIPISTON.NS",
    "TENNIND.NS",
    "RAMCOCEM.NS",
    "INOXINDIA.NS",
    "ELGIEQUIP.NS",
    "WELSPUNLIV.NS",
    "CHALET.NS",
    "DIACABS.NS",
    "LMW.NS",
    "JINDALSAW.NS",
    "GESHIP.NS",
    "HBLENGINE.NS",
    "CESC.NS",
    "KAJARIACER.NS",
    "PINELABS.NS",
    "FINCABLES.NS",
    "CASTROLIND.NS",
    "RATNAMANI.NS",
    "ATUL.NS",
    "AZAD.NS",
    "EIHOTEL.NS",
    "SHILPAMED.NS",
    "ERIS.NS",
    "TBOTEK.NS",
    "THELEELA.NS",
    "TRITURBINE.NS",
    "SARDAEN.NS",
    "FSL.NS",
    "BAYERCROP.NS",
    "SAMMAANCAP.NS",
    "SUNTV.NS",
    "ONESOURCE.NS",
    "AARTIIND.NS",
    "GMDCLTD.NS",
    "ZYDUSWELL.NS",
    "BEML.NS",
    "ECLERX.NS",
    "POLYMED.NS",
    "COHANCE.NS",
    "ASTRAZEN.NS",
    "DEVYANI.NS",
    "VTL.NS",
    "ALIVUS.NS",
    "THANGAMAYL.NS",
    "DEEPAKFERT.NS",
    "TRAVELFOOD.NS",
    "CHOICEIN.NS",
    "ABDL.NS",
    "OLAELEC.NS",
    "CHAMBLFERT.NS",
    "INDIACEM.NS",
    "JSWCEMENT.NS",
    "AGARWALEYE.NS",
    "CENTURYPLY.NS",
    "PARADEEP.NS",
    "BASF.NS",
    "MINDACORP.NS",
    "PSB.NS",
    "J&KBANK.NS",
    "GRWRHITECH.NS",
    "EMAMILTD.NS",
    "PGEL.NS",
    "KFINTECH.NS",
    "GPIL.NS",
    "NAVA.NS",
    "AVALON.NS",
    "APLLTD.NS",
    "FINEORG.NS",
    "KANSAINER.NS",
    "SYNGENE.NS",
    "DCMSHRIRAM.NS",
    "GSPL.NS",
    "TATACHEM.NS",
    "LTFOODS.NS",
    "ENGINERSIN.NS",
    "FIVESTAR.NS",
    "ARE&M.NS",
    "CARTRADE.NS",
    "MAHSCOOTER.NS",
    "SHAILY.NS",
    "AEQUS.NS",
    "KPITTECH.NS",
    "NATCOPHARM.NS",
    "HONASA.NS",
    "ABREL.NS",
    "USHAMART.NS",
    "MARKSANS.NS",
    "CONCORDBIO.NS",
    "BALRAMCHIN.NS",
    "JUBLPHARMA.NS",
    "APOLLO.NS",
    "SUDEEPPHRM.NS",
    "INGERRAND.NS",
    "NIVABUPA.NS",
    "RAINBOW.NS",
    "ATLANTAELE.NS",
    "CROMPTON.NS",
    "TMB.NS",
    "ARVIND.NS",
    "SHADOWFAX.NS",
    "CCL.NS",
    "CANHLIFE.NS",
    "KIRLOSBROS.NS",
    "CIEINDIA.NS",
    "VGUARD.NS",
    "JSWDULUX.NS",
    "JBMA.NS",
    "INDGN.NS",
    "NAZARA.NS",
    "MANYAVAR.NS",
    "ANURAS.NS",
    "GRAPHITE.NS",
    "KSB.NS",
    "PRUDENT.NS",
    "EIDPARRY.NS",
    "GALLANTT.NS",
    "BBOX.NS",
    "IGIL.NS",
    "SCI.NS",
    "PCJEWELLER.NS",
    "VENTIVE.NS",
    "CEATLTD.NS",
    "NSLNISP.NS",
    "SOBHA.NS",
    "DOMS.NS",
    "BLUESTONE.NS",
    "ACE.NS",
    "PRIVISCL.NS",
    "LUMAXTECH.NS",
    "TI.NS",
    "INOXWIND.NS",
    "SIGMAADV.NS",
    "HOMEFIRST.NS",
    "LLOYDSENGG.NS",
    "APTUS.NS",
    "RKFORGE.NS",
    "UTLSOLAR.NS",
    "GODREJAGRO.NS",
    "UJJIVANSFB.NS",
    "MANORAMA.NS",
    "VARROC.NS",
    "JSWHL.NS",
    "KTKBANK.NS",
    "EDELWEISS.NS",
    "WABAG.NS",
    "PCBL.NS",
    "JMFINANCIL.NS",
    "AMAGI.NS",
    "PARKHOSPS.NS",
    "NUVOCO.NS",
    "TRIDENT.NS",
    "GRAVITA.NS",
    "SKYGOLD.NS",
    "SOUTHBANK.NS",
    "ASKAUTOLTD.NS",
    "TEGA.NS",
    "BLUEDART.NS",
    "VIYASH.NS",
    "CYIENT.NS",
    "AKUMS.NS",
    "JPPOWER.NS",
    "QPOWER.NS",
    "UTIAMC.NS",
    "SHREEJISPG.NS",
    "PVRINOX.NS",
    "SIGNATURE.NS",
    "VOLTAMP.NS",
    "TECHNOE.NS",
    "IRCON.NS",
    "LLOYDSENT.NS",
    "SBFC.NS",
    "STAR.NS",
    "MGL.NS",
    "AFCONS.NS",
    "TITAGARH.NS",
    "IIFLCAPS.NS",
    "CANFINHOME.NS",
    "AVANTIFEED.NS",
    "KEC.NS",
    "JUBLINGREA.NS",
    "KRN.NS",
    "BLACKBUCK.NS",
    "WELENT.NS",
    "JKTYRE.NS",
    "TEJASNET.NS",
    "JWL.NS",
    "IEX.NS",
    "PGIL.NS",
    "ABLBL.NS",
    "RITES.NS",
    "AAVAS.NS",
    "WHIRLPOOL.NS",
    "ZENSARTECH.NS",
    "HCG.NS",
    "BBTC.NS",
    "ALKYLAMINE.NS",
    "RATEGAIN.NS",
    "OLECTRA.NS",
    "KIRLPNU.NS",
    "BLUEJET.NS",
    "SUDARSCHEM.NS",
    "BLS.NS",
    "KRBL.NS",
    "LOTUSDEV.NS",
    "FINPIPE.NS",
    "JAINREC.NS",
    "YATHARTH.NS",
    "ELECON.NS",
    "INTELLECT.NS",
    "MMTC.NS",
    "PRICOLLTD.NS",
    "SAREGAMA.NS",
    "SANDUMA.NS",
    "SANOFICONR.NS",
    "NCC.NS",
    "WEWORK.NS",
    "SMLMAH.NS",
    "MAHSEAMLES.NS",
    "THYROCARE.NS",
    "PNGJL.NS",
    "TIMETECHNO.NS",
    "RPOWER.NS",
    "TARIL.NS",
    "ICIL.NS",
    "BANCOINDIA.NS",
    "TSFINV.NS",
    "WAAREERTL.NS",
    "MAXESTATES.NS",
    "RELIGARE.NS",
    "GNFC.NS",
    "SWANCORP.NS",
    "JAYNECOIND.NS",
    "RAILTEL.NS",
    "BATAINDIA.NS",
    "FIRSTCRY.NS",
    "VESUVIUS.NS",
    "LEMONTREE.NS",
    "PRECWIRE.NS",
    "RELAXO.NS",
    "EQUITASBNK.NS",
    "GRINFRA.NS",
    "BALAMINES.NS",
    "WESTLIFE.NS",
    "ENTERO.NS",
    "ZEEL.NS",
    "TIPSMUSIC.NS",
    "EMBDL.NS",
    "V2RETAIL.NS",
    "ORKLAINDIA.NS",
    "GARFIBRES.NS",
    "EPL.NS",
    "MEDPLUS.NS",
    "BSOFT.NS",
    "MIDHANI.NS",
    "EUREKAFORB.NS",
    "STARCEMENT.NS",
    "DYNAMATECH.NS",
    "SONATSOFTW.NS",
    "AARTIPHARM.NS",
    "GPPL.NS",
    "SETL.NS",
    "RHIM.NS",
    "MAHLIFE.NS",
    "SKFINDIA.NS",
    "JKPAPER.NS",
    "UNIMECH.NS",
    "GAEL.NS",
    "NESCO.NS",
    "GALAXYSURF.NS",
    "AXISCADES.NS",
    "BORORENEW.NS",
    "SAFARI.NS",
    "SJS.NS",
    "KSHINTL.NS",
    "CELLO.NS",
    "POWERMECH.NS",
    "CERA.NS",
    "SKIPPER.NS",
    "IXIGO.NS",
    "NEWGEN.NS",
    "BLISSGVS.NS",
    "ETHOSLTD.NS",
    "SAPPHIRE.NS",
    "INDIASHLTR.NS",
    "SUPRIYA.NS",
    "GMRP&UI.NS",
    "TTML.NS",
    "SANOFI.NS",
    "NEPHROPLUS.NS",
    "MBAPL.NS",
    "DCBBANK.NS",
    "RAIN.NS",
    "BECTORFOOD.NS",
    "EBGNG.NS",
    "SFL.NS",
    "IMFA.NS",
    "SHARDACROP.NS",
    "INOXGREEN.NS",
    "TANLA.NS",
    "CYIENTDLM.NS",
    "RBA.NS",
    "EMIL.NS",
    "GOKULAGRO.NS",
    "AJAXENGG.NS",
    "CAMPUS.NS",
    "BIRLACORPN.NS",
    "SPARC.NS",
    "INNOVACAP.NS",
    "FCL.NS",
    "VMART.NS",
    "TFCILTD.NS",
    "ABFRL.NS",
    "CENTUM.NS",
    "GSFC.NS",
    "CEIGALL.NS",
    "BALUFORGE.NS",
    "DBL.NS",
    "JAIBALAJI.NS",
    "GANESHHOU.NS",
    "JKLAKSHMI.NS",
    "ACI.NS",
    "RCF.NS",
    "PRAJIND.NS",
    "HCC.NS",
    "SMARTWORKS.NS",
    "STYL.NS",
    "SUNFLAG.NS",
    "TRIVENI.NS",
    "NEOGEN.NS",
    "VIKRAMSOLR.NS",
    "SENCO.NS",
    "KPIGREEN.NS",
    "JUSTDIAL.NS",
    "ARVINDFASN.NS",
    "JINDWORLD.NS",
    "SHAKTIPUMP.NS",
    "ISGEC.NS",
    "LUMAXIND.NS",
    "JSFB.NS",
    "TVSSCS.NS",
    "GOKEX.NS",
    "KALPATARU.NS",
    "KRISHANA.NS",
    "PRSMJOHNSN.NS",
    "TRANSRAILL.NS",
    "INDIGOPNTS.NS",
    "FDC.NS",
    "GMMPFAUDLR.NS",
    "CCAVENUE.NS",
    "MSTCLTD.NS",
    "DBREALTY.NS",
    "FIEMIND.NS",
    "CSBBANK.NS",
    "LATENTVIEW.NS",
    "IONEXCHANG.NS",
    "VADILALIND.NS",
    "RENUKA.NS",
    "SAATVIKGL.NS",
    "MAPMYINDIA.NS",
    "IFBIND.NS",
    "THOMASCOOK.NS",
    "PURVA.NS",
    "HEG.NS",
    "MASTEK.NS",
    "GULFOILLUB.NS",
    "CARERATING.NS",
    "HAPPSTMNDS.NS",
    "WAKEFIT.NS",
    "ASHAPURMIN.NS",
    "RAYMOND.NS",
    "VRLLOG.NS",
    "SHARDAMOTR.NS",
    "EPIGRAL.NS",
    "QUESS.NS",
    "JAMNAAUTO.NS",
    "OPTIEMUS.NS",
    "MOIL.NS",
    "BOSCH-HCIL.NS",
    "MANINFRA.NS",
    "ELECTCAST.NS",
    "CRAMC.NS",
    "PDSL.NS",
    "TEXRAIL.NS",
    "ORCHPHARMA.NS",
    "SHILCTECH.NS",
    "LXCHEM.NS",
    "AGI.NS",
    "SURYAROSNI.NS",
    "PNCINFRA.NS",
    "SUBROS.NS",
    "PTC.NS",
    "DHANUKA.NS",
    "VIPIND.NS",
    "ELLEN.NS",
    "GREAVESCOT.NS",
    "MPSLTD.NS",
    "DATAMATICS.NS",
    "RAJTV.NS",
    "SWSOLAR.NS",
    "SUNTECK.NS",
    "INDIQUBE.NS",
    "NETWORK18.NS",
    "ORIANA.NS",
    "AVANTEL.NS",
    "EMUDHRA.NS",
    "KSL.NS",
    "RAYMONDLSL.NS",
    "TVSSRICHAK.NS",
    "63MOONS.NS",
    "RALLIS.NS",
    "MAHLOG.NS",
    "AHLUCONT.NS",
    "TARC.NS",
    "GHCL.NS",
    "TATVA.NS",
    "BAJAJELEC.NS",
    "SYMPHONY.NS",
    "SAMBHV.NS",
    "KOLTEPATIL.NS",
    "RTNPOWER.NS",
    "RTNINDIA.NS",
    "AARTIDRUGS.NS",
    "NACLIND.NS",
    "POLYPLEX.NS",
    "MIDWESTLTD.NS",
    "CMSINFO.NS",
    "IDEAFORGE.NS",
    "REFEX.NS",
    "SANGHVIMOV.NS",
    "ALOKINDS.NS",
    "CAPILLARY.NS",
    "SHAREINDIA.NS",
    "KSCL.NS",
    "JKIL.NS",
    "AURIONPRO.NS",
    "RAYMONDREL.NS",
    "TRUALT.NS",
    "STYRENIX.NS",
    "VAIBHAVGBL.NS",
    "HEMIPROP.NS",
    "HERITGFOOD.NS",
    "ANUP.NS",
    "JTLIND.NS",
    "VSTIND.NS",
    "LUXIND.NS",
    "EIEL.NS",
    "DBCORP.NS",
    "PACEDIGITK.NS",
    "CIGNITITEC.NS",
    "ANTELOPUS.NS",
    "AGIIL.NS",
    "SAMHI.NS",
    "KNRCON.NS",
    "NFL.NS",
    "PSPPROJECT.NS",
    "STEELCAS.NS",
    "ADVENZYMES.NS",
    "ZOTA.NS",
    "WEBELSOLAR.NS",
    "ARSSBL.NS",
    "ASHOKA.NS",
    "ROUTE.NS",
    "HGINFRA.NS",
    "RELTD.NS",
    "PRINCEPIPE.NS",
    "OSWALPUMPS.NS",
    "IMAGICAA.NS",
    "UEL.NS",
    "MONARCH.NS",
    "HIKAL.NS",
    "RSYSTEMS.NS",
    "PANAMAPET.NS",
    "INTERARCH.NS",
    "CRIZAC.NS",
    "SPORTKING.NS",
    "GATEWAY.NS",
    "DCAL.NS",
    "TALBROAUTO.NS",
    "VMARCIND.NS",
    "GANECOS.NS",
    "EUROPRATIK.NS",
    "GKENERGY.NS",
    "ORIENTCEM.NS",
    "PATELENG.NS",
    "KITEX.NS",
    "ROSSARI.NS",
    "BBL.NS",
    "ZAGGLE.NS",
    "OWAIS.NS",
    "SAKAR.NS",
    "EASEMYTRIP.NS",
    "JISLJALEQS.NS",
    "RELINFRA.NS",
    "PARKHOTELS.NS",
    "RAJESHEXPO.NS",
    "STALLION.NS",
    "EPACKPEB.NS",
    "ARKADE.NS",
    "REMUS.NS",
    "VENUSREM.NS",
    "BRIGHOTEL.NS",
    "EMSLIMITED.NS",
    "MAHASTEEL.NS",
    "SPANDANA.NS",
    "TCIEXP.NS",
    "SHRINGARMS.NS",
    "SHANTIGOLD.NS",
    "SILVERTUC.NS",
    "GREENPANEL.NS",
    "TEAMLEASE.NS",
    "SAKSOFT.NS",
    "ALLCARGO.NS",
    "NUCLEUS.NS",
    "VIDYAWIRES.NS",
    "BGRENERGY.NS",
    "HATHWAY.NS",
    "INDIAGLYCO.NS",
    "AWFIS.NS",
    "TINNARUBR.NS",
    "GRMOVER.NS",
    "NGLFINE.NS",
    "TARSONS.NS",
    "CAPACITE.NS",
    "KAPSTON.NS",
    "MOL.NS",
    "SAHANA.NS",
    "QUADFUTURE.NS",
    "GARUDA.NS",
    "STUDDS.NS",
    "ASIANHOTNR.NS",
    "VIKRAN.NS",
    "INFOBEAN.NS",
    "MBEL.NS",
    "MCLOUD.NS",
    "SIGNPOST.NS",
    "ALLTIME.NS",
    "EXPLEOSOL.NS",
    "GKSL.NS",
    "IZMO.NS",
    "DEN.NS",
    "MANAKCOAT.NS",
    "SOLARWORLD.NS",
    "BIL.NS",
    "IVALUE.NS",
    "FAZE3Q.NS",
    "ARROWGREEN.NS",
    "COMSYN.NS",
    "APEX.NS",
    "SARTELE.NS",
    "BALAJITELE.NS",
    "WAAREEINDO.NS",
    "MICEL.NS",
    "MASTERTR.NS",
    "LAXMIDENTL.NS",
    "SRM.NS",
    "TAC.NS",
    "JYOTIRES.BO",
    "JINDALPHOT.NS",
    "ARIS.NS",
    "MAMATA.NS",
    "JARO.NS",
    "UNITEDPOLY.NS",
    "CONSOFINVT.NS",
    "SWARAJ.NS",
    "GANESHBE.NS",
    "REGAAL.NS",
    "LGHL.NS",
    "SAHAJSOLAR.NS",
    "BORANA.NS",
    "DRONE.NS",
    "IFBAGRO.NS",
    "ORICONENT.NS",
    "PRECOT.NS",
    "GEMAROMA.NS",
    "AHCL.NS",
    "NDTV.NS",
    "PROSTARM.NS",
    "PANACHE.NS",
    "SPCL.NS",
    "EXCELSOFT.NS",
    "SUMEETINDS.NS",
    "SEJALLTD.NS",
    "SCODATUBES.NS",
    "MEIL.NS",
    "PCCL.NS",
    "SUPREMEPWR.NS",
    "TIRUPATI.NS",
    "NEETUYOSHI.BO",
    "DENTA.NS",
    "ADVANCE.NS",
    "PROZONER.NS",
    "PATELRMART.NS",
    "SJLOGISTIC.NS",
    "EXHICON.BO",
    "LAXMIINDIA.NS",
    "GANESHCP.NS",
    "HERANBA.NS",
    "WTICAB.NS",
    "GTPL.NS",
    "TVTODAY.NS",
    "FABTECH.NS",
    "INDOFARM.NS",
    "INNOVANA.NS",
    "AQYLON.NS",
    "SHREERAMA.NS",
    "TBI.NS",
    "TGL.NS",
    "PHANTOMFX.NS",
    "SHREEKARNI.NS",
    "GLOTTIS.NS",
    "PRATHAM.NS",
    "ONMOBILE.NS",
    "ZEEMEDIA.NS",
    "SURANI.NS",
    "ENIL.NS",
    "INDOTHAI.NS",
    "SAAKSHI.NS",
    "BMWVENTLTD.NS",
    "SAIFL.NS",
    "RKSWAMY.NS",
    "TCL.NS",
    "DISHTV.NS",
    "IGCL.NS",
    "REFRACTORY.NS",
    "SHERA.NS",
    "NEWJAISA.NS",
    "WINSOL.NS",
    "RBMINFRA.NS",
    "TRUST.NS",
    "ROCKINGDCE.NS",
    "ESCONET.NS",
    "ZTECH.NS",
    "CINELINE.NS",
    "PROV.NS",
    "SYSTANGO.NS",
    "SKP.NS",
    "SHEMAROO.NS",
    "SADHAV.NS",
    "PURVFLEXI.NS",
    "TERASOFT.NS",
    "TUNWAL.NS",
    "NIRMAN.NS",
    "URBAN.NS",
    "VERTOZ.NS",
    "HILINFRA.NS",
    "PRLIND.NS",
    "ROXHITECH.NS",
    "QMSMEDI.NS",
    "MVKAGRO.NS",
    "GLOBECIVIL.NS",
    "GICL.NS",
    "ONDOOR.NS",
    "PARAGON.NS",
    "SONAMAC.NS",
    "LLOYDS.NS",
    "PARIN.NS",
    "SPECTSTM.NS",
    "ZEAL.NS",
    "UFO.NS",
    "SHREEOSFM.NS",
    "YASHOPTICS.NS",
    "SSFL.NS",
    "SYLVANPLY.NS",
    "SHIGAN.NS",
    "PULZ.NS",
    "QUESTLAB.NS",
    "VMSTMT.NS",
    "RULKA.NS",
    "RADIOCITY.NS",
    "RBS.NS",
    "TAKE.NS",
    "MAXPOSURE.NS",
    "PRITIKA.NS",
    "CADSYS.NS",
    "PRIZOR.NS",
    "UNIHEALTH.NS",
    "SHRITECH.NS",
    "WOMANCART.NS",
    "QUICKTOUCH.NS",
    "SOTAC.NS",
    "PRAMARA.NS",
    "SWASTIK.NS",
    "BTML.NS",
    "DTL.NS",
    "DTIL.NS",
    "SRIVASAVI.NS",
    "TRANSTEEL.NS",
    "SCML.NS",
    "MOXSH.NS",
    "PARTYCRUS.NS",
    "DGCONTENT.NS",
    "TIPSFILMS.NS",
    "MCON.NS",
    "VITAL.NS",
    "MUKTAARTS.NS",
    "ZENITHDRUG.NS",
    "RCDL.NS",
    "NAMAN.NS",
    "VEEKAYEM.NS",
    "RILINFRA.NS",
    "SATIPOLY.NS",
    "MEDIORG.NS",
    "SAMBHAAV.NS",
    "PRECISION.NS",
    "BAGFILMS.NS",
    "PRESSTONIC.NS",
    "GRAPHISAD.NS",
    "PENTAGON.NS",
    "SIDDHIKA.NS",
    "VERTEXPLUS.NS",
    "PATTECH.NS",
    "SYNOPTICS.NS",
    "RADIOWALLA.NS",
    "PROLIFE.NS",
    "SILKFLEX.NS",
    "SLONE.NS",
    "SEL.NS",
    "UCL.NS",
    "CINEVISTA.NS",
    "MAITREYA.NS",
    "REXPIPES.NS",
    "SONUINFRA.NS",
    "OMFURN.NS",
    "VELS.NS",
    "TRIDHYA.NS",
    "GSTL.NS",
    "VIAZ.NS",
    "UMA.NS",
    "SHEETAL.NS",
    "SIGNORIA.NS",
    "VSCL.NS",
    "WINNY.NS",
    "YUDIZ.NS",
    "SERVICE.NS",
    "SANGANI.NS",
    "MICROPRO.NS",
    "TAPIFRUIT.NS",
    "CYBERMEDIA.NS",
    "VISAMAN.NS",
    "SABAR.NS",
    "YCCL.NS",
    "SPRL.NS",
    "NIDAN.NS",
    "SHANTHALA.NS",
    "INSPIRE.NS",
    "TIMESCAN.NS",
    "MAKS.NS",
    "MEGAFLEX.NS",
    "VERITAAS.NS",
    "BIRDYS.NS",
    "POLYSIL.NS",
    "SHUBHLAXMI.NS",
    "CBAZAAR.NS",
    "DHTL.NS",
    "KANDARP.NS",
    "OLIL.NS",
    "SUNREST.NS",
    "QFIL.NS",
    "DNAMEDIA.NS",
    "VILINBIO.NS",
    "QUADPRO.NS",
    "PLADAINFO.NS",
    "NEXTMEDIA.NS",
    "PNC.NS",
    "MPTODAY.NS",
    "TRANSWIND.NS",
    "RITEZONE.NS",
    "SAROJA.NS",
    "VIVO.NS",
    "SILLYMONKS.NS",
    "RADAAN.NS",
    "SMVD.NS",
    "TVVISION.NS",
    "CREATIVEYE.NS",
    "ACCORD.NS",
    "SABEVENTS.NS",
    "JALAN.NS",
    "VASA.NS",
    "AKZOINDIA.NS",
    "GUJGASLTD.NS",
    "VISASTEEL.NS",
    "AAKAAR.NS",
    "AARADHYA.NS",
    "ABHAPOWER.NS",
    "ACCPL.NS",
    "ACTIVEINFR.NS",
    "ADDICTIVE.NS",
    "AERON.NS",
    "AESTHETIK.NS",
    "AGARWALTUF.NS",
    "AKANKSHA.NS",
    "ALCODIS.NS",
    "AMBANIORGO.NS",
    "AMCL.NS",
    "ANONDITA.NS",
    "ANYA.NS",
    "APEXECO.NS",
    "APRAMEYA.NS",
    "ARCIIL.NS",
    "ARHAM.NS",
    "ARUNAYA.NS",
    "ARVINDPORT.NS",
    "ASHALOG.NS",
    "ATCENERGY.NS",
    "AUSL.NS",
    "AVIANSH.NS",
    "BAGDIGITAL.NS",
    "BALAJIPHOS.NS",
    "BALCO.NS",
    "BARFLEX.NS",
    "BHADORA.NS",
    "BHARATCOAL.NS",
    "BIKEWO.NS",
    "BLUEWATER.NS",
    "BOSS.NS",
    "BRACEPORT.NS",
    "BULKCORP.NS",
    "C2C.NS",
    "CEDAAR.NS",
    "CHAMUNDA.NS",
    "CHANDAN.NS",
    "CHETANA.NS",
    "CLASSICEIL.NS",
    "CONNPLEX.NS",
    "CORONA.NS",
    "CUDML.NS",
    "CURIS.NS",
    "CURRENT.NS",
    "DANISH.NS",
    "DCCL.NS",
    "DECCANTRAN.NS",
    "DELTIC.NS",
    "DHARIWAL.NS",
    "DIRL.NS",
    "DIVINEHIRA.NS",
    "DIVYADHAN.NS",
    "ECOLINE.NS",
    "EEPL.NS",
    "ELGNZ.NS",
    "EMAPARTNER.NS",
    "ENVIRO.NS",
    "ESPRIT.NS",
    "ETL.NS",
    "ETML.NS",
    "EXCELLENT.NS",
    "FINBUD.NS",
    "FLYSBS.NS",
    "FOCE.NS",
    "FORCAS.NS",
    "FORGEAUTO.NS",
    "FRESHARA.NS",
    "GAJANAND.NS",
    "GANESHIN.NS",
    "GANGABATH.NS",
    "GCHOTELS.NS",
    "GML.NS",
    "GREENLEAF.NS",
    "GURUNANAK.NS",
    "HDFC.NS",
    "HPTL.NS",
    "HVAX.NS",
    "IBULHSGFIN.NS",
    "IDEALTECHO.NS",
    "IDENTICAL.NS",
    "INFLUX.NS",
    "INNOMET.NS",
    "INTEGRITY.NS",
    "IPHL.NS",
    "ITTL.NS",
    "IWARE.NS",
    "JAINIK.NS",
    "JAYBEE.NS",
    "JAYESH.NS",
    "JEYYAM.NS",
    "JYOTIGLOBL.NS",
    "KALANA.NS",
    "KATARIA.NS",
    "KAYTEX.NS",
    "KEN.NS",
    "KKJEWELS.NS",
    "LAKSHYA.NS",
    "LAMOSAIC.NS",
    "MACOBSTECH.NS",
    "MAXVOLT.NS",
    "MAYASHEEL.NS",
    "MEDISTEP.NS",
    "MGSL.NS",
    "MIEL.NS",
    "MMEL.NS",
    "MONOLITH.NS",
    "MPEL.NS",
    "MRIL.NS",
    "MUNISH.NS",
    "MYMUDRA.NS",
    "NAMOEWASTE.NS",
    "NEELAM.NS",
    "NEPTUNE.NS",
    "NIKITA.NS",
    "NMSTEEL.NS",
    "NRVANDANA.NS",
    "OBSCP.NS",
    "ONYX.NS",
    "OPTIVALUE.NS",
    "OSELDEVICE.NS",
    "PARAMATRIX.NS",
    "PARAMOUNT.NS",
    "PARAMPARA.NS",
    "PARTH.NS",
    "PATILAUTOM.NS",
    "PELATRO.NS",
    "PHOGLOBAL.NS",
    "POSITRON.NS",
    "PPSL.NS",
    "PRANIK.NS",
    "PREMIUM.NS",
    "PRIMECAB.NS",
    "PROFX.NS",
    "PSFL.NS",
    "PSRAJ.NS",
    "PURPLEUTED.NS",
    "PUSHPA.NS",
    "QVCEL.NS",
    "RAJINDLTD.NS",
    "RAJPUTANA.NS",
    "RAPIDFLEET.NS",
    "RAPPID.NS",
    "READYMIX.NS",
    "REXPRO.NS",
    "RICHA.NS",
    "RNFI.NS",
    "RNPL.NS",
    "ROYALARC.NS",
    "RTL.NS",
    "SACHEEROME.NS",
    "SAFEENTP.NS",
    "SAHASRA.NS",
    "SAJHOTELS.NS",
    "SAMAY.NS",
    "SATECH.NS",
    "SATKARTAR.NS",
    "SATTVAENGG.NS",
    "SAVY.NS",
    "SAWALIYA.NS",
    "SDREAMS.NS",
    "SELLOWRAP.NS",
    "SFML.NS",
    "SHEEL.NS",
    "SHETHJI.NS",
    "SHIVASHRIT.NS",
    "SHKSIL.NS",
    "SHRIAHIMSA.NS",
    "SHUBHSHREE.NS",
    "SIDDHICOTS.NS",
    "SILKY.NS",
    "SMARTEN.NS",
    "SNEHAA.NS",
    "SPPPOLY.NS",
    "SPUNWEB.NS",
    "SSEGL.NS",
    "STUDIOLSD.NS",
    "SUBAHOTELS.NS",
    "SUNLITE.NS",
    "SUNTECH.NS",
    "TANKUP.NS",
    # Quality Alpha screen additions
    "ESABINDIA.NS",
    "KINGFA.NS",
    "AVL.NS",
    "TANFACIND.BO",
    "KOVAI.NS",
    "TCI.NS",
    "TIMEX.NS",
    "GUJTHEM.NS",
    "STYLAMIND.NS",
    "SHANTIGEAR.NS",
    "GOLDIAM.NS",
    "SWARAJENG.NS",
    "KPL.NS",
    "CARYSIL.NS",
    "GRAUWEIL.NS",
    "JASH.NS",
    "APCOTEXIND.NS",
    "ADOR.NS",
    "DRAGARWQ.NS",
    "SIRCA.NS",
    # Quality Alpha screen additions (Set 2: #51-#96)
    "PIXTRANS.NS",
    "THEJO.NS",
    "KMCSHIL.NS",
    "FREDUN.NS",
    "DYCL.NS",
    "SIKA.NS",
    "MACPOWER.NS",
    "RACLGEAR.NS",
    "TITANBIO.BO",
    "DISAQ.NS",
    "MODISONLTD.NS",
    "KPEL.NS",
    "FRONTSP.NS",
    "CEINSYS.NS",
    "BHARATSE.NS",
    "FERMENTA.NS",
    "TAALTECH.NS",
    "DSSL.NS",
    "BENARAS.NS",
    "3BBLACKBIO.NS",
    "506528.BO",
    "ADCINDIA.BO",
    "SUNSHIEL.NS",
    "RADHIKAJWE.NS",
    "RAJOOENG.NS",
    "BSHSL.NS",
    "VIKRAMTH.BO",
    "PREMIERPOL.NS",
    "UNIABEXAL.BO",
    "INDOAMIN.NS",
    "KOTHARIPET.NS",
    "AXTEL.NS",
    "GLOBAL.NS",
    "KSOLVES.NS",
    "UNIVASTU.NS",
    "STELLANT.BO",
    "DHABRIYA.NS",
    "HIGHENE.BO",
]







_duplicate_tickers = sorted({symbol for symbol in TICKERS if TICKERS.count(symbol) > 1})

if _duplicate_tickers:

    raise AssertionError(f"Duplicate tickers in TICKERS: {', '.join(_duplicate_tickers)}")



# --- MULTIBAGGER HUNT FRAMEWORK (MARCH 2026) ---

# Derived from structural framework for falling markets.

MULTIBAGGER_HUNT = {

    "desc": "Comprehensive Hunt for structural multibaggers (V4.1)",

    "filters": {

        "sales_growth_5y_min": 0.15,  # Annualized Sales > 15%

        "pat_growth_5y_min": 0.15,  # PAT Growth > 15%

        "roe_min": 0.15,  # ROE > 15%

        "roce_min": 0.15,  # ROCE > 15%

        "peg_max": 1.0,  # PEG < 1

        "debt_equity_max": 0.50,  # Debt/Equity < 0.5

        "pledge_pct_max": 0.0,  # Strictly zero pledge

        "promoter_pct_min": 50.0,  # Promoter skin in the game

        "cfo_to_pat_min": 0.8,  # OCF / Net Profit > 0.8

        "market_cap_max": 5000,  # Small/Mid cap space

        "piotroski_min": 6,

    },

}



# Targeted hunting grounds for structural multibaggers

SECTORS = [

    # Defense Electronics & Systems

    "BEL.NS",

    "DATAPATTNS.NS",

    "PARAS.NS",

    "ZENTEC.NS",

    "ASTRAMICRO.NS",

    # Specialty Chemicals (China+1 survivors)

    "CLEAN.NS",

    "NAVINFLUOR.NS",

    "VINATIORGA.NS",

    "DEEPAKNTR.NS",

    "AETHER.NS",

    # Healthcare & Diagnostics (Immune consumption)

    "METROPOLIS.NS",

    "VIJAYA.NS",

    "NH.NS",

    "KIMS.NS",

    # EMS / Electronics Mfg (PLI tailwinds)

    "DIXON.NS",

    "KAYNES.NS",

    "AMBER.NS",

    "SYRMA.NS",

    # Agrochemicals (Rural recovery)

    "PIIND.NS",

    "SUMICHEM.NS",

    # Capital Goods / Capex Cycle

    "GRINDWELL.NS",

    "AIAENG.NS",

    "CARBORUNIV.NS",

    # Building Materials (Real Estate proxy)

    "ASTRAL.NS",

    "SUPREMEIND.NS",

    "POLYCAB.NS",

    # Platform Businesses (Market infrastructure)

    "CDSL.NS",

    "CAMS.NS",

    "BSE.NS",

    # Branded Consumption / FMCG Midcap

    "RADICO.NS",

    "BIKAJI.NS",

    "DODLA.NS",

    "JYOTHYLAB.NS",

]



# Guard: warn if SECTORS contains tickers already in TICKERS (prevents double-scanning)

_sectors_in_tickers = sorted(set(SECTORS) & set(TICKERS))

if _sectors_in_tickers:

    import warnings

    warnings.warn(

        f"SECTORS contains {len(_sectors_in_tickers)} tickers already in TICKERS: "

        f"{_sectors_in_tickers[:5]}{'...' if len(_sectors_in_tickers) > 5 else ''}",

        stacklevel=1,

    )
